### ISSUE TITLE
Add function to overlay histogram

### ISSUE THREAD

**Issue by fsolt** [sammo3182/interplot#13]
http://rpubs.com/kohske/dual_axis_in_ggplot2 is a bit of a start

**Comment by fsolt** [comment]
Also see http://www.r-bloggers.com/ggextra-r-package-for-adding-marginal-histograms-to-ggplot2/ .  The ggplot_build() function may be particularly helpful

**Comment by fsolt** [comment]
per Berry, Golder, and Milton 2012 doi:10.1017/S0022381612000199

**Comment by fsolt** [comment]
see also http://polmeth.wustl.edu/files/polmeth/interaction_02_25_2016.pdf 
Very nice use of inset histograms, but not clear how they did it.  Plus other comments on use of interactions that we should consider incorporating if possible.

**Comment by fsolt** [comment]
here's the conversation on Twitter: https://twitter.com/fredericksolt/status/677554984792141824

**Comment by sammo3182** [comment]
I successfully replicated Jens, Mummolo, and Xu. The key looks to be draw the histogram FIRST. So, we may need a separate function from interplot.plot to draw such type of combined plot.

**Comment by fsolt** [comment]
Commit your replication code to /dev?  I'd like to look it over too.

**Comment by sammo3182** [comment]
Users can either use the model data or external source to superimpose the histogram.
