### ISSUE TITLE
Question regarding conditioning marginal effects on values of other variables

### ISSUE THREAD

**Issue by breschke** [sammo3182/interplot#24]
In your [vignette](https://cran.r-project.org/web/packages/interplot/vignettes/interplot-vignette.html), you state that interplot "plots the changes in the coefficient of one variable in a two-way interaction term conditional on the value of the other included variable." In each example provided, only two variables are included as independent variables (or a single variable with a quadratic). How does your package accommodate multiple regression with more variables than those involved in the interaction(s) of interest? Particularly, at what values does the package condition 'controls' in computing marginal effects? Lastly, do the methods for nonlinear models account for the inherent interdependence among variables?

**Comment by sammo3182** [comment]
Sorry for the late reply. While we only present the relevant variables in the plots. All the controls are involved when simulating the conditioning effect. The controls are holding as the default values of the model functions (median for `lm` and `glm`, if I remember that correctly).
