### ISSUE TITLE
Installation of github version fails in R 3.4.1 on Ubuntu

### ISSUE THREAD

**Issue by breschke** [sammo3182/interplot#25]
Attempting to install the github version of interplot I got the following error:

```devtools::install_github("sammo3182/inrerplot")
Downloading github repo twitter/BreakoutDetection@master
Error in system(full, intern = quiet, ignore.stderr = quiet, ...) : 
  error in running command

sessionInfo()
R version 3.4.1 (2017-06-30)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 16.04.3 LTS
...
```

Searching for this error, I found a workaround on https://github.com/RevolutionAnalytics/RRO/issues/37:

> To work around this issue, set options(unzip = 'internal') before calling install_github. (See #37 and hadley/devtools#406 )

After running the following, the github installation works as expected.
```
options(unzip = 'internal')
devtools::install_github("sammo3182/inrerplot")
```

**Comment by sammo3182** [comment]
Please see nsgrantham's answer at https://github.com/r-lib/devtools/issues/1722.
