### ISSUE TITLE
add quick review of lit on interactions in vignette

### ISSUE THREAD

**Issue by fsolt** [sammo3182/interplot#3]
and a brief discussion of use of interaction terms to README

**Comment by fsolt** [comment]
Don't forget Berry, Golder, and Milton (2012) in JOP

**Comment by fsolt** [comment]
also http://onlinelibrary.wiley.com/doi/10.1111/ajps.12123/abstract
http://www.polmeth.wustl.edu/files/polmeth/interaction_02_25_2016.pdf

**Comment by fsolt** [comment]
also http://jee3.web.rice.edu/interaction-overconfidence.pdf

**Comment by sammo3182** [comment]
@fsolt I added a review in the vignette. It doesn't cover the Hainmueller et al. 2016 and Esarey and Sumner 2016, since I haven't incorporated the methods of these works into the `interplot` function yet and neither has formally published.
