### ISSUE TITLE
How to remove printed max-min CI bottom-right corner?

### ISSUE THREAD

**Issue by gijsschumacher** [sammo3182/interplot#30]
Since recently the interplot function prints a confidence interval (numerically) in the bottom right corner of the interaction plot, e.g. CI(Max-Min): [number,number]. How do I remove this? Looking into the code the ci_diff value regulates this, but I don't know what value to give it to stop printing this CI.

**Comment by sammo3182** [comment]
In the current version, we didn't set the option to turn it off with the consideration that it largely shows the lowest boundary to identify a conditional effect, and that is, in many cases, why you need the `interplot`. Do you mind if I ask why you want to get rid of it or what problem you indicated for showing this information?

**Comment by gijsschumacher** [comment]
Hi, thanks for the quick answer. Ok, i misunderstood  what the CI values stood for. My initial thought was that the numbers refer to the CI that is plotted (incidentally they were similar to the CI of the difference). So my suggestion would be to print CI(diff), to make it clearer. Still, I would like to be able to manipulate the printing of this function. I am trying to plot a whole number of interaction plots, and then they take up quite some space. Also, most effects are clearly insignificant, so i feel the CI info is a bit redundant. Thanks for making interplot!

**Comment by sammo3182** [comment]
Got it @gijsschumacher . Thank you for the suggestion. I'll see if I could add an argument for switching on/off the CI(diff) in a future version.

**Comment by sammo3182** [comment]
`interplot` estimates the marginal effects of the contribution of the conditioned variable at both the minimum and  maximum values of the conditioning variable (a.k.a. the moderator). The CI(max - min) provides the confidence interval of the difference between these two values. If the interval includes 0, it suggests there is no statistical difference before and after the conditional effect is applied, and vise versa. In a more simplified version, you may argue that if the CI contains 0, then the variance of the conditioning variable in its range does not significantly change the effect of the conditioned variable.

**Comment by christian2adam** [comment]
thanks a lot for this. Great clarification. Got it!

**Comment by tannenberg** [comment]
Thanks for this exchange, I find the CI valuable most of the time but remove them sometimes when I want to keep the plot super clean. @gijsschumacher you can always just set caption to "" as that is were the info is printed. So: + labs(caption = "") should do the trick.

**Comment by arminmertens** [comment]
Hi, just stumbled upon this thread. Thanks @sammo3182 for the clarification of what the CI means. Adding to @tannenberg 's answer, I actually prefer using `labs(caption = element_blank())` as it also removes the empty space in the bottom right corner.
