### ISSUE TITLE
set.seed() in interplot() functions

### ISSUE THREAD

**Issue by mnwright** [sammo3182/interplot#33]
In several places the package sets a seed in the `interplot()`function, e.g. here: https://github.com/sammo3182/interplot/blob/4050557959cfe7d68cbf7043fe1a6baeca6db447/R/Interplot_default.R#L66

This is bad practice because you interfere with the user-set seed. Example: 
````R
set.seed(42)

data(mtcars)
m_cyl <- lm(mpg ~ wt * cyl, data = mtcars)
interplot(m = m_cyl, var1 = 'cyl', var2 = 'wt')

rnorm(1)
````
gives the same random number as
````R
set.seed(43)

data(mtcars)
m_cyl <- lm(mpg ~ wt * cyl, data = mtcars)
interplot(m = m_cyl, var1 = 'cyl', var2 = 'wt')

rnorm(1)
````
which shouldn't be the case.

**Comment by sammo3182** [comment]
Thank you for the suggestion. The goal of `interplot` is to simplify users' job to create accurate moderation effect plots and maintain reproducibility. Also, frankly, I don't believe it matters so very much as long as there is no theoretical reason to pick one seed rather than another. The package does not plan to add a special argument about seed setting so far.

**Comment by mnwright** [comment]
Thanks for the close without further discussion. 👎 

> Also, frankly, I don't believe it matters so very much as long as there is no theoretical reason to pick one seed rather than another.

That's not the point. The user expects a different result for a different user-set seed and you should not interfere with that. 

As an extreme example, imagine a simulation study with repeated calls to `interplot()` (for whatever reason). Each subsequent simulation run except the first one will give the exact same result because you set the same seed every time.

**Comment by fsolt** [comment]
I just pushed a commit to address this by dropping the set.seed() call

**Comment by mnwright** [comment]
Thanks!
